[package]
name = "quake-inverse-sqrt"
description = "A rust implementation of the Quake Inverse Square root alghorithm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
